import "./globals.css";
import { Aldrich } from "next/font/google";

const roboto = Aldrich({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Jasiel Pool Party",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
